services:
  db:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_DB: gopher_social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: S3cureP@ssw0rd!
    ports:
      - "5432:5432"
    volumes:
      - ./compose-files/postgres:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
