addr:        ":8080"
apiURL:      "localhost:8080"
frontendURL: "http://localhost:5173"
env:         "development"
db:
  addr:         "postgres://admin:S3cureP%40ssw0rd%21@localhost/gopher_social?sslmode=disable"
  maxOpenConns: 30
  maxIdleConns: 30
  maxIdleTime:  "15m"
redisCfg:
  addr:    "localhost:6379"
  pw:      ""
  db:      0
  enabled: false
mail:
  exp:       72h
  fromEmail: ""
  sendGrid:
    apiKey: "test"
  mailTrap:
    apiKey: "test"
auth:
  basic:
    user: "admin"
    pass: "admin"
  token:
    secret: "example"
    exp:    72h
    iss:    "gophersocial"
rateLimiter:
  RequestsPerTimeFrame: 20
  TimeFrame:            5s
  Enabled:              true